services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appartments
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]

  web:
    container_name: web
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:5000"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appartments
    depends_on:
      db:
        condition: service_healthy
